CAP4770 Final Project
Data source
https://www.datasciencedata.com/auto-insurance-churn-data
Created by: Matt Strenges, Tuyet Phan, and Mary Szabo
Summer 2023

In [3]:
import pylab
import matplotlib
import pandas as pd
import numpy as np
import os
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split,RandomizedSearchCV, train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from scipy.stats import randint
from IPython.display import Image

df = pd.read_csv("full_auto_insurance_data.csv")

In [4]:
display(df) #Original DF

,INDIVIDUAL_ID,acct_terminated,ADDRESS_ID,CURR_ANN_AMT,DAYS_TENURE,CUST_ORIG_DATE,AGE_IN_YEARS,DATE_OF_BIRTH,SOCIAL_SECURITY_NUMBER,LATITUDE,...,COUNTY,INCOME,HAS_CHILDREN,LENGTH_OF_RESIDENCE,MARITAL_STATUS,HOME_MARKET_VALUE,HOME_OWNER,COLLEGE_DEGREE,GOOD_CREDIT,ACCT_SUSPD_DATE
0,2.213000e+11,NaN,5.213000e+11,818.87,1454.0,2018-12-09,44.474,1978-06-23,608-XX-7640,32.578829,...,Kaufman,22500.00,1.0,15.0,Married,50000 - 74999,1.0,1.0,1.0,NaN
1,2.213001e+11,NaN,5.213001e+11,974.19,1795.0,2018-01-02,72.559,1950-05-30,342-XX-6908,32.732209,...,Dallas,27500.00,0.0,2.0,Single,50000 - 74999,1.0,0.0,0.0,NaN
2,2.213007e+11,NaN,5.213002e+11,967.37,4818.0,2009-09-23,55.444,1967-07-07,240-XX-9224,32.819777,...,Dallas,42500.00,0.0,10.0,Married,75000 - 99999,1.0,0.0,0.0,NaN
3,2.213016e+11,NaN,5.213006e+11,992.40,130.0,2022-07-25,53.558,1969-05-25,775-XX-6249,32.684065,...,Tarrant,125000.00,1.0,6.0,Married,175000 - 199999,1.0,0.0,1.0,2021-12-22
4,2.213016e+11,NaN,5.213006e+11,784.63,5896.0,2006-10-11,50.220,1972-09-25,629-XX-7298,32.751398,...,Tarrant,87500.00,1.0,4.0,Married,225000 - 249999,1.0,1.0,1.0,NaN
5,2.213027e+11,NaN,5.213010e+11,909.91,484.0,2021-08-05,32.641,1990-04-20,194-XX-6050,NaN,...,Dallas,52500.00,0.0,2.0,Married,125000 - 149999,1.0,0.0,1.0,NaN
6,2.213007e+11,NaN,5.213003e+11,1084.04,2896.0,2014-12-28,70.806,1952-02-29,653-XX-7262,33.006985,...,Denton,125000.00,1.0,8.0,Married,100000 - 124999,1.0,0.0,1.0,NaN
7,2.213022e+11,NaN,5.213008e+11,1277.37,4096.0,2011-09-15,45.969,1976-12-24,163-XX-1670,33.085901,...,Collin,47500.00,0.0,12.0,Married,125000 - 149999,1.0,0.0,1.0,NaN
8,2.213029e+11,NaN,5.213011e+11,917.20,2107.0,2017-02-24,56.389,1966-07-27,621-XX-5572,32.828468,...,Tarrant,47500.00,0.0,6.0,Single,50000 - 74999,1.0,1.0,1.0,2022-12-01
9,2.213012e+11,NaN,5.213005e+11,1095.39,3387.0,2013-08-24,64.307,1958-08-28,793-XX-1178,32.753978,...,Dallas,32500.00,0.0,15.0,Married,25000 - 49999,1.0,0.0,0.0,NaN
10,2.213015e+11,NaN,5.213005e+11,966.83,80.0,2022-09-13,55.444,1967-07-07,677-XX-1586,32.805436,...,Tarrant,80372.17,0.0,6.8,NaN,50000 - 74999,0.0,1.0,0.0,2022-09-16
11,2.213013e+11,NaN,5.213005e+11,905.03,5336.0,2008-04-23,66.639,1956-04-29,188-XX-6698,32.645107,...,Tarrant,125000.00,0.0,15.0,Married,125000 - 149999,1.0,1.0,1.0,NaN
12,2.213013e+11,NaN,5.213005e+11,619.60,1606.0,2018-07-10,NaN,1993-11-21,133-XX-4591,32.711729,...,Dallas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2.213031e+11,NaN,5.213013e+11,590.95,1606.0,2018-07-10,55.444,1967-07-07,777-XX-2081,NaN,...,Parker,70000.00,0.0,0.0,NaN,NaN,0.0,0.0,1.0,NaN
14,2.213020e+11,NaN,5.213007e+11,462.91,6020.0,2006-06-09,41.473,1981-06-22,299-XX-2622,33.089878,...,Denton,37500.00,1.0,6.0,Married,75000 - 99999,1.0,1.0,1.0,NaN
15,2.213028e+11,NaN,5.213010e+11,722.08,374.0,2021-11-23,69.139,1953-10-29,335-XX-8227,33.168202,...,Collin,62500.00,1.0,5.0,Single,100000 - 124999,1.0,1.0,1.0,NaN
16,2.213021e+11,NaN,5.213008e+11,569.83,107.0,2022-08-17,32.559,1990-05-20,277-XX-1871,32.854910,...,Tarrant,80372.17,0.0,6.8,NaN,150000 - 174999,0.0,1.0,1.0,NaN
17,2.213009e+11,NaN,5.213003e+11,961.04,80.0,2022-09-13,55.444,1967-07-07,563-XX-7554,NaN,...,Dallas,47500.00,0.0,0.0,NaN,NaN,0.0,0.0,1.0,2022-06-12
18,2.213014e+11,NaN,5.213005e+11,841.02,150.0,2022-07-05,59.053,1963-11-28,551-XX-2401,32.841713,...,Dallas,57500.00,0.0,11.0,Single,150000 - 174999,0.0,0.0,1.0,NaN
19,2.213015e+11,NaN,5.213005e+11,943.55,2409.0,2016-04-28,55.444,1967-07-07,455-XX-5888,NaN,...,Dallas,80372.17,0.0,6.8,NaN,250000 - 274999,0.0,0.0,1.0,NaN
20,2.213031e+11,NaN,5.213013e+11,741.67,4711.0,2010-01-08,43.723,1979-03-24,734-XX-3221,32.851905,...,Dallas,125000.00,1.0,10.0,Single,225000 - 249999,1.0,0.0,1.0,NaN
21,2.213015e+11,NaN,5.213005e+11,1398.72,5049.0,2009-02-04,40.969,1981-12-23,633-XX-7001,32.675671,...,Tarrant,125000.00,1.0,15.0,Married,75000 - 99999,1.0,1.0,1.0,NaN
22,2.213032e+11,NaN,5.213014e+11,913.66,6226.0,2005-11-15,60.559,1962-05-27,424-XX-2825,32.639399,...,Tarrant,47500.00,0.0,12.0,Married,50000 - 74999,1.0,0.0,1.0,NaN
23,2.213010e+11,NaN,5.213004e+11,438.24,1018.0,2020-02-18,48.893,1974-01-22,950-XX-8716,32.807283,...,Dallas,70000.00,0.0,6.0,Married,150000 - 174999,0.0,0.0,1.0,NaN
24,2.213008e+11,NaN,5.213003e+11,953.30,5463.0,2007-12-18,67.806,1955-02-28,585-XX-2402,32.869218,...,Tarrant,125000.00,0.0,9.0,Married,75000 - 99999,1.0,0.0,1.0,NaN
25,2.213024e+11,NaN,5.213009e+11,725.16,3336.0,2013-10-14,38.220,1984-09-22,423-XX-4997,32.841944,...,Tarrant,70000.00,0.0,7.0,Married,75000 - 99999,1.0,0.0,1.0,NaN
26,2.213000e+11,NaN,5.213000e+11,716.71,5654.0,2007-06-10,48.893,1974-01-22,479-XX-4835,NaN,...,Tarrant,87500.00,1.0,0.0,Single,NaN,0.0,0.0,0.0,2021-12-20
27,2.213020e+11,NaN,5.213007e+11,1103.39,6291.0,2005-09-11,NaN,1982-02-27,540-XX-5795,32.841068,...,Tarrant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2.213011e+11,NaN,5.213004e+11,795.03,2409.0,2016-04-28,55.444,1967-07-07,627-XX-9534,32.832474,...,Dallas,32500.00,0.0,6.8,NaN,75000 - 99999,0.0,0.0,1.0,NaN
29,2.213015e+11,NaN,5.213006e+11,1322.51,6291.0,2005-09-11,55.138,1967-10-27,250-XX-8931,NaN,...,Dallas,37500.00,1.0,7.0,Single,100000 - 124999,1.0,1.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2280291,2.213002e+11,NaN,5.213001e+11,1072.36,1813.0,2017-12-15,34.472,1988-06-21,630-XX-8564,NaN,...,Collin,125000.00,1.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN
2280292,2.213006e+11,NaN,5.213002e+11,908.39,3762.0,2012-08-14,59.138,1963-10-28,506-XX-6711,32.862185,...,Tarrant,47500.00,1.0,15.0,Married,75000 - 99999,1.0,0.0,1.0,NaN
2280293,2.213002e+11,NaN,5.213001e+11,1105.36,3101.0,2014-06-06,51.890,1971-01-24,364-XX-8511,32.683451,...,Tarrant,87500.00,1.0,12.0,Married,75000 - 99999,1.0,0.0,1.0,NaN
2280294,2.213003e+11,NaN,5.213001e+11,790.96,2385.0,2016-05-22,NaN,1983-04-19,505-XX-4395,32.918277,...,Dallas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2280295,2.213022e+11,NaN,5.213008e+11,1290.31,282.0,2022-02-23,56.559,1966-05-26,595-XX-3128,32.660717,...,Dallas,5000.00,1.0,15.0,Single,50000 - 74999,1.0,0.0,0.0,NaN
2280296,2.213002e+11,NaN,5.213001e+11,1251.92,506.0,2021-07-14,33.306,1989-08-20,782-XX-8679,32.758413,...,Kaufman,42500.00,0.0,15.0,Married,50000 - 74999,1.0,0.0,1.0,NaN
2280297,2.213030e+11,NaN,5.213012e+11,998.89,140.0,2022-07-15,56.389,1966-07-27,646-XX-6005,32.581784,...,Dallas,57500.00,1.0,5.0,Single,25000 - 49999,1.0,0.0,1.0,NaN
2280298,2.213012e+11,NaN,5.213005e+11,989.45,840.0,2020-08-14,43.472,1979-06-24,710-XX-2382,32.733825,...,Kaufman,125000.00,1.0,3.0,Single,125000 - 149999,1.0,1.0,1.0,NaN
2280299,2.213030e+11,NaN,5.213013e+11,918.77,3963.0,2012-01-26,45.054,1977-11-23,154-XX-9474,32.777825,...,Dallas,12500.00,1.0,4.0,Single,100000 - 124999,1.0,0.0,0.0,NaN
2280300,2.213006e+11,NaN,5.213002e+11,1257.56,98.0,2022-08-26,44.808,1978-02-21,795-XX-4476,33.040822,...,Parker,27500.00,1.0,6.8,Single,25000 - 49999,0.0,1.0,0.0,2021-12-23
2280301,2.213004e+11,NaN,5.213001e+11,726.39,2241.0,2016-10-13,42.472,1980-06-23,683-XX-5655,33.006400,...,Collin,87500.00,1.0,3.0,Married,200000 - 224999,1.0,0.0,1.0,NaN
2280302,2.213020e+11,NaN,5.213007e+11,808.34,4697.0,2010-01-22,69.388,1953-07-30,169-XX-1714,33.169976,...,Collin,70000.00,1.0,1.0,Married,125000 - 149999,1.0,0.0,1.0,NaN
2280303,2.213032e+11,NaN,5.213014e+11,591.31,2398.0,2016-05-09,31.053,1991-11-21,130-XX-4154,32.732201,...,Kaufman,12500.00,1.0,5.0,Single,1000 - 24999,0.0,0.0,1.0,NaN
2280304,2.213018e+11,NaN,5.213007e+11,832.68,88.0,2022-09-05,41.969,1980-12-23,281-XX-4340,32.649631,...,Tarrant,87500.00,1.0,4.0,Married,100000 - 124999,1.0,1.0,1.0,NaN
2280305,2.213000e+11,NaN,5.213000e+11,877.39,161.0,2022-06-24,55.444,1967-07-07,491-XX-1532,32.699260,...,Tarrant,80372.17,0.0,0.0,NaN,25000 - 49999,1.0,0.0,0.0,NaN
2280306,2.213005e+11,NaN,5.213002e+11,308.37,2061.0,2017-04-11,55.556,1967-05-27,556-XX-9387,32.953847,...,Denton,70000.00,1.0,14.0,Married,100000 - 124999,1.0,1.0,1.0,NaN
2280307,2.213031e+11,NaN,5.213013e+11,1047.71,6291.0,2005-09-11,57.221,1965-09-26,686-XX-4444,33.001304,...,Dallas,70000.00,1.0,2.0,Married,175000 - 199999,1.0,1.0,1.0,NaN
2280308,2.213001e+11,NaN,5.213000e+11,931.09,6291.0,2005-09-11,82.557,1940-06-02,386-XX-4360,32.940467,...,Rockwall,47500.00,1.0,15.0,Married,50000 - 74999,1.0,1.0,1.0,2022-03-26
2280309,2.213016e+11,NaN,5.213006e+11,510.96,278.0,2022-02-27,NaN,1998-06-27,575-XX-4965,32.896625,...,Tarrant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2280310,2.213023e+11,NaN,5.213008e+11,775.55,2097.0,2017-03-06,56.222,1966-09-26,740-XX-8182,32.859100,...,Tarrant,80372.17,0.0,1.0,Single,100000 - 124999,1.0,0.0,1.0,NaN
2280311,2.213004e+11,NaN,5.213001e+11,960.69,723.0,2020-12-09,55.444,1967-07-07,313-XX-4211,33.106566,...,Collin,70000.00,1.0,4.0,Single,100000 - 124999,1.0,0.0,1.0,NaN
2280312,2.213007e+11,NaN,5.213002e+11,1259.90,803.0,2020-09-20,55.444,1967-07-07,836-XX-1003,32.678483,...,Dallas,27500.00,1.0,3.0,Single,50000 - 74999,1.0,0.0,1.0,NaN
2280313,2.213015e+11,NaN,5.213005e+11,604.09,3261.0,2013-12-28,77.473,1945-07-01,498-XX-6384,32.972007,...,Dallas,87500.00,0.0,1.0,Married,125000 - 149999,1.0,0.0,1.0,NaN
2280314,2.213026e+11,NaN,5.213009e+11,1255.57,3403.0,2013-08-08,41.221,1981-09-22,960-XX-3949,32.902815,...,Dallas,125000.00,0.0,12.0,Married,125000 - 149999,1.0,1.0,1.0,NaN
2280315,2.213003e+11,NaN,5.213001e+11,1041.94,5341.0,2008-04-18,NaN,1980-05-07,764-XX-2229,NaN,...,Tarrant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2280316,2.213008e+11,NaN,5.213003e+11,1104.10,1258.0,2019-06-23,52.389,1970-07-26,730-XX-5654,32.892940,...,Tarrant,87500.00,1.0,11.0,Single,75000 - 99999,1.0,1.0,1.0,NaN
2280317,2.213004e+11,NaN,5.213001e+11,1189.74,142.0,2022-07-13,37.388,1985-07-22,306-XX-2712,33.184917,...,Collin,80372.17,0.0,6.8,NaN,100000 - 124999,0.0,1.0,1.0,NaN
2280318,2.213024e+11,NaN,5.213009e+11,362.14,1606.0,2018-07-10,55.444,1967-07-07,800-XX-2726,33.019653,...,Collin,80372.17,0.0,1.0,NaN,75000 - 99999,1.0,0.0,1.0,NaN
2280319,2.213006e+11,NaN,5.213002e+11,611.69,6291.0,2005-09-11,NaN,1998-11-09,198-XX-4107,33.038807,...,Collin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2280320,2.213016e+11,NaN,5.213006e+11,829.86,2504.0,2016-01-24,63.639,1959-04-29,520-XX-7573,33.146851,...,Denton,225000.00,1.0,4.0,Married,200000 - 224999,1.0,0.0,1.0,NaN

In [5]:
#Processing Data
df.loc[df['CURR_ANN_AMT'].isnull(), 'CURR_ANN_AMT'] = 931.06 #mean CURR_ANN_AMT is 931
df.loc[df['DAYS_TENURE'].isnull(), 'DAYS_TENURE'] = 3482.62 # mean DAYS_TENURE is 3482
df.loc[df['AGE_IN_YEARS'].isnull(), 'AGE_IN_YEARS'] = 55.44 # mean AGE_IN_YEARS is 55.44
df.loc[df['INCOME'].isnull(), 'INCOME'] = 80372.36 # mean INCOME is 80372.36
df.loc[df['HAS_CHILDREN'].isnull(), 'HAS_CHILDREN'] = 0.0 # mode HAS_CHILDREN is 0
df.loc[df['LENGTH_OF_RESIDENCE'].isnull(), 'LENGTH_OF_RESIDENCE'] = 6.80 # mean LENGTH_OF_RESIDENCE is 6.80
df.loc[df['MARITAL_STATUS'].isnull(), 'MARITAL_STATUS'] = "Married" # mode MARITAL_STATUS is Married
df.loc[df['MARITAL_STATUS']=="Married", 'MARITAL_STATUS'] = 1 #Married is a 1
df.loc[df['MARITAL_STATUS']=="Single", 'MARITAL_STATUS'] = 0 #Single is a 0
df.loc[df['HOME_MARKET_VALUE'].isnull(), 'HOME_MARKET_VALUE'] = "75000 - 99999" # mode HOME_MARKET_VALUE is 75000 - 99999
df.loc[df['HOME_OWNER'].isnull(), 'HOME_OWNER'] = 1 # mode HOME_OWNER is 1
df.loc[df['COLLEGE_DEGREE'].isnull(), 'COLLEGE_DEGREE'] = 0 # mode COLLEGE_DEGREE is 0
df.loc[df['GOOD_CREDIT'].isnull(), 'GOOD_CREDIT'] = 1 # mode GOOD_CREDIT is 1
df.loc[df['ACCT_SUSPD_DATE'].notnull(), 'acct_terminated'] = 1 #terminated=1
df.loc[df['ACCT_SUSPD_DATE'].isnull(), 'acct_terminated'] = 0 #not terminated=0
df = df.drop('ACCT_SUSPD_DATE', axis=1)
df = df.drop('DATE_OF_BIRTH', axis=1)
df = df.drop('SOCIAL_SECURITY_NUMBER', axis=1)
df = df.drop('LATITUDE', axis=1)
df = df.drop('LONGITUDE', axis=1)
df = df.drop('STREET_ADDRESS', axis=1)
df = df.drop('CITY', axis=1)
df = df.drop('STATE', axis=1)
df = df.drop('COUNTY', axis=1)
df = df.dropna(axis=0)
pd.set_option('display.max_columns', None) #Displays every column
df #Processed DF

#These data columns were not changed as I don't believe we are using them and changing them would be complicated.
#ADDRESS_ID was not changed
#CUST_ORIG_DATE was not changed
#DATE_OF_BIRTH was not changed
#SOCIAL_SECURITY_NUMBER was not changed
#LATITUDE & LONGITUDE were not changed
#STREET, CITY, STATE & COUNTY were not changed

,INDIVIDUAL_ID,acct_terminated,ADDRESS_ID,CURR_ANN_AMT,DAYS_TENURE,CUST_ORIG_DATE,AGE_IN_YEARS,INCOME,HAS_CHILDREN,LENGTH_OF_RESIDENCE,MARITAL_STATUS,HOME_MARKET_VALUE,HOME_OWNER,COLLEGE_DEGREE,GOOD_CREDIT
0,2.213000e+11,0.0,5.213000e+11,818.87,1454.0,2018-12-09,44.474,22500.00,1.0,15.0,1,50000 - 74999,1.0,1.0,1.0
1,2.213001e+11,0.0,5.213001e+11,974.19,1795.0,2018-01-02,72.559,27500.00,0.0,2.0,0,50000 - 74999,1.0,0.0,0.0
2,2.213007e+11,0.0,5.213002e+11,967.37,4818.0,2009-09-23,55.444,42500.00,0.0,10.0,1,75000 - 99999,1.0,0.0,0.0
3,2.213016e+11,1.0,5.213006e+11,992.40,130.0,2022-07-25,53.558,125000.00,1.0,6.0,1,175000 - 199999,1.0,0.0,1.0
4,2.213016e+11,0.0,5.213006e+11,784.63,5896.0,2006-10-11,50.220,87500.00,1.0,4.0,1,225000 - 249999,1.0,1.0,1.0
5,2.213027e+11,0.0,5.213010e+11,909.91,484.0,2021-08-05,32.641,52500.00,0.0,2.0,1,125000 - 149999,1.0,0.0,1.0
6,2.213007e+11,0.0,5.213003e+11,1084.04,2896.0,2014-12-28,70.806,125000.00,1.0,8.0,1,100000 - 124999,1.0,0.0,1.0
7,2.213022e+11,0.0,5.213008e+11,1277.37,4096.0,2011-09-15,45.969,47500.00,0.0,12.0,1,125000 - 149999,1.0,0.0,1.0
8,2.213029e+11,1.0,5.213011e+11,917.20,2107.0,2017-02-24,56.389,47500.00,0.0,6.0,0,50000 - 74999,1.0,1.0,1.0
9,2.213012e+11,0.0,5.213005e+11,1095.39,3387.0,2013-08-24,64.307,32500.00,0.0,15.0,1,25000 - 49999,1.0,0.0,0.0
10,2.213015e+11,1.0,5.213005e+11,966.83,80.0,2022-09-13,55.444,80372.17,0.0,6.8,1,50000 - 74999,0.0,1.0,0.0
11,2.213013e+11,0.0,5.213005e+11,905.03,5336.0,2008-04-23,66.639,125000.00,0.0,15.0,1,125000 - 149999,1.0,1.0,1.0
12,2.213013e+11,0.0,5.213005e+11,619.60,1606.0,2018-07-10,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
13,2.213031e+11,0.0,5.213013e+11,590.95,1606.0,2018-07-10,55.444,70000.00,0.0,0.0,1,75000 - 99999,0.0,0.0,1.0
14,2.213020e+11,0.0,5.213007e+11,462.91,6020.0,2006-06-09,41.473,37500.00,1.0,6.0,1,75000 - 99999,1.0,1.0,1.0
15,2.213028e+11,0.0,5.213010e+11,722.08,374.0,2021-11-23,69.139,62500.00,1.0,5.0,0,100000 - 124999,1.0,1.0,1.0
16,2.213021e+11,0.0,5.213008e+11,569.83,107.0,2022-08-17,32.559,80372.17,0.0,6.8,1,150000 - 174999,0.0,1.0,1.0
17,2.213009e+11,1.0,5.213003e+11,961.04,80.0,2022-09-13,55.444,47500.00,0.0,0.0,1,75000 - 99999,0.0,0.0,1.0
18,2.213014e+11,0.0,5.213005e+11,841.02,150.0,2022-07-05,59.053,57500.00,0.0,11.0,0,150000 - 174999,0.0,0.0,1.0
19,2.213015e+11,0.0,5.213005e+11,943.55,2409.0,2016-04-28,55.444,80372.17,0.0,6.8,1,250000 - 274999,0.0,0.0,1.0
20,2.213031e+11,0.0,5.213013e+11,741.67,4711.0,2010-01-08,43.723,125000.00,1.0,10.0,0,225000 - 249999,1.0,0.0,1.0
21,2.213015e+11,0.0,5.213005e+11,1398.72,5049.0,2009-02-04,40.969,125000.00,1.0,15.0,1,75000 - 99999,1.0,1.0,1.0
22,2.213032e+11,0.0,5.213014e+11,913.66,6226.0,2005-11-15,60.559,47500.00,0.0,12.0,1,50000 - 74999,1.0,0.0,1.0
23,2.213010e+11,0.0,5.213004e+11,438.24,1018.0,2020-02-18,48.893,70000.00,0.0,6.0,1,150000 - 174999,0.0,0.0,1.0
24,2.213008e+11,0.0,5.213003e+11,953.30,5463.0,2007-12-18,67.806,125000.00,0.0,9.0,1,75000 - 99999,1.0,0.0,1.0
25,2.213024e+11,0.0,5.213009e+11,725.16,3336.0,2013-10-14,38.220,70000.00,0.0,7.0,1,75000 - 99999,1.0,0.0,1.0
26,2.213000e+11,1.0,5.213000e+11,716.71,5654.0,2007-06-10,48.893,87500.00,1.0,0.0,0,75000 - 99999,0.0,0.0,0.0
27,2.213020e+11,0.0,5.213007e+11,1103.39,6291.0,2005-09-11,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
28,2.213011e+11,0.0,5.213004e+11,795.03,2409.0,2016-04-28,55.444,32500.00,0.0,6.8,1,75000 - 99999,0.0,0.0,1.0
29,2.213015e+11,0.0,5.213006e+11,1322.51,6291.0,2005-09-11,55.138,37500.00,1.0,7.0,0,100000 - 124999,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2280291,2.213002e+11,0.0,5.213001e+11,1072.36,1813.0,2017-12-15,34.472,125000.00,1.0,0.0,1,75000 - 99999,0.0,0.0,0.0
2280292,2.213006e+11,0.0,5.213002e+11,908.39,3762.0,2012-08-14,59.138,47500.00,1.0,15.0,1,75000 - 99999,1.0,0.0,1.0
2280293,2.213002e+11,0.0,5.213001e+11,1105.36,3101.0,2014-06-06,51.890,87500.00,1.0,12.0,1,75000 - 99999,1.0,0.0,1.0
2280294,2.213003e+11,0.0,5.213001e+11,790.96,2385.0,2016-05-22,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
2280295,2.213022e+11,0.0,5.213008e+11,1290.31,282.0,2022-02-23,56.559,5000.00,1.0,15.0,0,50000 - 74999,1.0,0.0,0.0
2280296,2.213002e+11,0.0,5.213001e+11,1251.92,506.0,2021-07-14,33.306,42500.00,0.0,15.0,1,50000 - 74999,1.0,0.0,1.0
2280297,2.213030e+11,0.0,5.213012e+11,998.89,140.0,2022-07-15,56.389,57500.00,1.0,5.0,0,25000 - 49999,1.0,0.0,1.0
2280298,2.213012e+11,0.0,5.213005e+11,989.45,840.0,2020-08-14,43.472,125000.00,1.0,3.0,0,125000 - 149999,1.0,1.0,1.0
2280299,2.213030e+11,0.0,5.213013e+11,918.77,3963.0,2012-01-26,45.054,12500.00,1.0,4.0,0,100000 - 124999,1.0,0.0,0.0
2280300,2.213006e+11,1.0,5.213002e+11,1257.56,98.0,2022-08-26,44.808,27500.00,1.0,6.8,0,25000 - 49999,0.0,1.0,0.0
2280301,2.213004e+11,0.0,5.213001e+11,726.39,2241.0,2016-10-13,42.472,87500.00,1.0,3.0,1,200000 - 224999,1.0,0.0,1.0
2280302,2.213020e+11,0.0,5.213007e+11,808.34,4697.0,2010-01-22,69.388,70000.00,1.0,1.0,1,125000 - 149999,1.0,0.0,1.0
2280303,2.213032e+11,0.0,5.213014e+11,591.31,2398.0,2016-05-09,31.053,12500.00,1.0,5.0,0,1000 - 24999,0.0,0.0,1.0
2280304,2.213018e+11,0.0,5.213007e+11,832.68,88.0,2022-09-05,41.969,87500.00,1.0,4.0,1,100000 - 124999,1.0,1.0,1.0
2280305,2.213000e+11,0.0,5.213000e+11,877.39,161.0,2022-06-24,55.444,80372.17,0.0,0.0,1,25000 - 49999,1.0,0.0,0.0
2280306,2.213005e+11,0.0,5.213002e+11,308.37,2061.0,2017-04-11,55.556,70000.00,1.0,14.0,1,100000 - 124999,1.0,1.0,1.0
2280307,2.213031e+11,0.0,5.213013e+11,1047.71,6291.0,2005-09-11,57.221,70000.00,1.0,2.0,1,175000 - 199999,1.0,1.0,1.0
2280308,2.213001e+11,1.0,5.213000e+11,931.09,6291.0,2005-09-11,82.557,47500.00,1.0,15.0,1,50000 - 74999,1.0,1.0,1.0
2280309,2.213016e+11,0.0,5.213006e+11,510.96,278.0,2022-02-27,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
2280310,2.213023e+11,0.0,5.213008e+11,775.55,2097.0,2017-03-06,56.222,80372.17,0.0,1.0,0,100000 - 124999,1.0,0.0,1.0
2280311,2.213004e+11,0.0,5.213001e+11,960.69,723.0,2020-12-09,55.444,70000.00,1.0,4.0,0,100000 - 124999,1.0,0.0,1.0
2280312,2.213007e+11,0.0,5.213002e+11,1259.90,803.0,2020-09-20,55.444,27500.00,1.0,3.0,0,50000 - 74999,1.0,0.0,1.0
2280313,2.213015e+11,0.0,5.213005e+11,604.09,3261.0,2013-12-28,77.473,87500.00,0.0,1.0,1,125000 - 149999,1.0,0.0,1.0
2280314,2.213026e+11,0.0,5.213009e+11,1255.57,3403.0,2013-08-08,41.221,125000.00,0.0,12.0,1,125000 - 149999,1.0,1.0,1.0
2280315,2.213003e+11,0.0,5.213001e+11,1041.94,5341.0,2008-04-18,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
2280316,2.213008e+11,0.0,5.213003e+11,1104.10,1258.0,2019-06-23,52.389,87500.00,1.0,11.0,0,75000 - 99999,1.0,1.0,1.0
2280317,2.213004e+11,0.0,5.213001e+11,1189.74,142.0,2022-07-13,37.388,80372.17,0.0,6.8,1,100000 - 124999,0.0,1.0,1.0
2280318,2.213024e+11,0.0,5.213009e+11,362.14,1606.0,2018-07-10,55.444,80372.17,0.0,1.0,1,75000 - 99999,1.0,0.0,1.0
2280319,2.213006e+11,0.0,5.213002e+11,611.69,6291.0,2005-09-11,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
2280320,2.213016e+11,0.0,5.213006e+11,829.86,2504.0,2016-01-24,63.639,225000.00,1.0,4.0,1,200000 - 224999,1.0,0.0,1.0

In [6]:
#col_names = [ 'CURR_ANN_AMT', 'DAYS_TENURE', 'AGE_IN_YEARS', 'INCOME', 'HAS_CHILDREN', 'LENGTH_OF_RESIDENCE',   'HOME_OWNER', 'COLLEGE_DEGREE', 'GOOD_CREDIT']
cols = ['CURR_ANN_AMT', 'DAYS_TENURE', 'AGE_IN_YEARS', 'INCOME', 'HAS_CHILDREN', 'LENGTH_OF_RESIDENCE',  'HOME_OWNER', 'COLLEGE_DEGREE', 'GOOD_CREDIT']
X = df[cols]
y = df.acct_terminated
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.817075381233

In [7]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

             precision    recall  f1-score   support

        0.0       0.90      0.89      0.90    603253
        1.0       0.25      0.28      0.26     80843

avg / total       0.82      0.82      0.82    684096

In [8]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [9]:
y_pred2 = rf.predict(X_test)
accuracy2 = accuracy_score(y_test, y_pred2)
print("Random Forest Accuracy:", accuracy2)

Random Forest Accuracy: 0.875765974366

In [10]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred2))

             precision    recall  f1-score   support

        0.0       0.90      0.97      0.93    603253
        1.0       0.44      0.19      0.27     80843

avg / total       0.85      0.88      0.85    684096

Oversampling

In [11]:
# https://machinelearningmastery.com/random-oversampling-and-undersampling-for-imbalanced-classification/

from imblearn.over_sampling import RandomOverSampler
from collections import Counter
# from sklearn.model_selection import train_test_split

# Separate the independent variables from the dependent variable
X_over = df.drop('acct_terminated', axis=1)  # Features (independent variables)
y_over = df['acct_terminated']  # Target variable (dependent variable)

# Create the RandomOverSampler instance targeting the minority class
oversampler = RandomOverSampler(sampling_strategy='minority')

# Apply oversampling to the dataset
X_resampled, y_resampled = oversampler.fit_resample(X_over, y_over)

print("Before oversampling: ", Counter(y_over))
print("After oversampling: ", Counter(y_resampled))

ModuleNotFoundError: No module named 'imblearn'

In [ ]:
# Convert the resampled arrays back to DataFrames
X_resampled_df = pd.DataFrame(X_resampled, columns=X_over.columns)
y_resampled_df = pd.DataFrame(y_resampled, columns=['acct_terminated'])

resampled_df = pd.concat([X_resampled_df, y_resampled_df], axis=1)

print(resampled_df)

In [ ]:
resampled_df.to_csv('oversampling_data.csv', index=False)

In [ ]:
df_over = pd.read_csv('oversampling_data.csv')

In [ ]:
cols = ['CURR_ANN_AMT', 'DAYS_TENURE', 'AGE_IN_YEARS', 'INCOME', 'HAS_CHILDREN', 'LENGTH_OF_RESIDENCE',  'HOME_OWNER', 'COLLEGE_DEGREE', 'GOOD_CREDIT']
X_over = df[cols]
y_over = df.acct_terminated
X_train, X_test, y_train, y_test = train_test_split(X_over, y_over, test_size=0.2, random_state=1)

# Create the DecisionTreeClassifier instance
model = DecisionTreeClassifier()

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict on the test data
preds = model.predict(X_test)

accuracy = accuracy_score(y_test, preds)
print('Decision Tree accuracy:', accuracy)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, preds))

In [ ]:
# Randomly sample 10% of the data for faster testing
sampled_df = df.sample(frac=0.1, random_state=1)

cols = ['CURR_ANN_AMT', 'DAYS_TENURE', 'AGE_IN_YEARS', 'INCOME', 'HAS_CHILDREN', 'LENGTH_OF_RESIDENCE', 'HOME_OWNER', 'COLLEGE_DEGREE', 'GOOD_CREDIT']
X_over = sampled_df[cols]
y_over = sampled_df['acct_terminated']

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_over, y_over, test_size=0.2, random_state=1)

# Create the RandomForestClassifier instance with n_jobs=-1 for parallel processing
model = RandomForestClassifier(n_estimators=100, n_jobs=-1)

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict on the test data
preds = model.predict(X_test)

accuracy = accuracy_score(y_test, preds)
print('Random Forest accuracy:', accuracy)

In [ ]:
print(classification_report(y_test, preds))

Undersampling

In [12]:
#Before I undersample, I want to see the starting values for terminated vs active accounts 
#There table terminated accounts 269,259 initially before rows with NaN were deleted. 
terminatedCount = len(df[df["acct_terminated"]==1])
print(terminatedCount)
activeCount = len(df[df["acct_terminated"]==0])
print(activeCount)

269259
2011061

In [15]:
#For undersampling, the number of tuples of terminated and active accounts should be the same
#After removing the NaN rows, we are only left with 27,542 terminated accounts and 220220 active accounts
#Next, we need the number of active accouts to be equal to the number of terminated accounts. 
active = df[df['acct_terminated'] == 0]
active = active.head(269259) #take the first 269259 rows
terminated = df[df['acct_terminated'] == 1]

In [16]:
#Combine the active and terminated dataframes
frames = [active, terminated]
df_undersample = pd.concat(frames)
df_undersample

,INDIVIDUAL_ID,acct_terminated,ADDRESS_ID,CURR_ANN_AMT,DAYS_TENURE,CUST_ORIG_DATE,AGE_IN_YEARS,INCOME,HAS_CHILDREN,LENGTH_OF_RESIDENCE,MARITAL_STATUS,HOME_MARKET_VALUE,HOME_OWNER,COLLEGE_DEGREE,GOOD_CREDIT
0,2.213000e+11,0.0,5.213000e+11,818.87,1454.0,2018-12-09,44.474,22500.00,1.0,15.0,1,50000 - 74999,1.0,1.0,1.0
1,2.213001e+11,0.0,5.213001e+11,974.19,1795.0,2018-01-02,72.559,27500.00,0.0,2.0,0,50000 - 74999,1.0,0.0,0.0
2,2.213007e+11,0.0,5.213002e+11,967.37,4818.0,2009-09-23,55.444,42500.00,0.0,10.0,1,75000 - 99999,1.0,0.0,0.0
4,2.213016e+11,0.0,5.213006e+11,784.63,5896.0,2006-10-11,50.220,87500.00,1.0,4.0,1,225000 - 249999,1.0,1.0,1.0
5,2.213027e+11,0.0,5.213010e+11,909.91,484.0,2021-08-05,32.641,52500.00,0.0,2.0,1,125000 - 149999,1.0,0.0,1.0
6,2.213007e+11,0.0,5.213003e+11,1084.04,2896.0,2014-12-28,70.806,125000.00,1.0,8.0,1,100000 - 124999,1.0,0.0,1.0
7,2.213022e+11,0.0,5.213008e+11,1277.37,4096.0,2011-09-15,45.969,47500.00,0.0,12.0,1,125000 - 149999,1.0,0.0,1.0
9,2.213012e+11,0.0,5.213005e+11,1095.39,3387.0,2013-08-24,64.307,32500.00,0.0,15.0,1,25000 - 49999,1.0,0.0,0.0
11,2.213013e+11,0.0,5.213005e+11,905.03,5336.0,2008-04-23,66.639,125000.00,0.0,15.0,1,125000 - 149999,1.0,1.0,1.0
12,2.213013e+11,0.0,5.213005e+11,619.60,1606.0,2018-07-10,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
13,2.213031e+11,0.0,5.213013e+11,590.95,1606.0,2018-07-10,55.444,70000.00,0.0,0.0,1,75000 - 99999,0.0,0.0,1.0
14,2.213020e+11,0.0,5.213007e+11,462.91,6020.0,2006-06-09,41.473,37500.00,1.0,6.0,1,75000 - 99999,1.0,1.0,1.0
15,2.213028e+11,0.0,5.213010e+11,722.08,374.0,2021-11-23,69.139,62500.00,1.0,5.0,0,100000 - 124999,1.0,1.0,1.0
16,2.213021e+11,0.0,5.213008e+11,569.83,107.0,2022-08-17,32.559,80372.17,0.0,6.8,1,150000 - 174999,0.0,1.0,1.0
18,2.213014e+11,0.0,5.213005e+11,841.02,150.0,2022-07-05,59.053,57500.00,0.0,11.0,0,150000 - 174999,0.0,0.0,1.0
19,2.213015e+11,0.0,5.213005e+11,943.55,2409.0,2016-04-28,55.444,80372.17,0.0,6.8,1,250000 - 274999,0.0,0.0,1.0
20,2.213031e+11,0.0,5.213013e+11,741.67,4711.0,2010-01-08,43.723,125000.00,1.0,10.0,0,225000 - 249999,1.0,0.0,1.0
21,2.213015e+11,0.0,5.213005e+11,1398.72,5049.0,2009-02-04,40.969,125000.00,1.0,15.0,1,75000 - 99999,1.0,1.0,1.0
22,2.213032e+11,0.0,5.213014e+11,913.66,6226.0,2005-11-15,60.559,47500.00,0.0,12.0,1,50000 - 74999,1.0,0.0,1.0
23,2.213010e+11,0.0,5.213004e+11,438.24,1018.0,2020-02-18,48.893,70000.00,0.0,6.0,1,150000 - 174999,0.0,0.0,1.0
24,2.213008e+11,0.0,5.213003e+11,953.30,5463.0,2007-12-18,67.806,125000.00,0.0,9.0,1,75000 - 99999,1.0,0.0,1.0
25,2.213024e+11,0.0,5.213009e+11,725.16,3336.0,2013-10-14,38.220,70000.00,0.0,7.0,1,75000 - 99999,1.0,0.0,1.0
27,2.213020e+11,0.0,5.213007e+11,1103.39,6291.0,2005-09-11,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
28,2.213011e+11,0.0,5.213004e+11,795.03,2409.0,2016-04-28,55.444,32500.00,0.0,6.8,1,75000 - 99999,0.0,0.0,1.0
29,2.213015e+11,0.0,5.213006e+11,1322.51,6291.0,2005-09-11,55.138,37500.00,1.0,7.0,0,100000 - 124999,1.0,1.0,1.0
30,2.213007e+11,0.0,5.213002e+11,839.85,3879.0,2012-04-19,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
31,2.213029e+11,0.0,5.213011e+11,908.89,6291.0,2005-09-11,53.725,27500.00,1.0,15.0,0,75000 - 99999,1.0,0.0,1.0
32,2.213006e+11,0.0,5.213002e+11,885.99,662.0,2021-02-08,108.641,125000.00,1.0,4.0,1,75000 - 99999,1.0,0.0,1.0
33,2.213026e+11,0.0,5.213009e+11,862.42,824.0,2020-08-30,32.969,37500.00,0.0,15.0,1,25000 - 49999,1.0,0.0,1.0
34,2.213012e+11,0.0,5.213004e+11,1144.91,261.0,2022-03-16,89.388,22500.00,0.0,15.0,1,100000 - 124999,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2279945,2.213003e+11,1.0,5.213001e+11,1082.37,5628.0,2007-07-06,69.306,27500.00,1.0,12.0,0,150000 - 174999,1.0,0.0,1.0
2279946,2.213020e+11,1.0,5.213007e+11,1036.65,92.0,2022-09-01,43.053,250000.00,1.0,5.0,1,175000 - 199999,1.0,0.0,1.0
2279954,2.213001e+11,1.0,5.213000e+11,1181.57,6291.0,2005-09-11,81.558,57500.00,0.0,15.0,1,50000 - 74999,1.0,0.0,1.0
2279957,2.213028e+11,1.0,5.213010e+11,1003.55,6291.0,2005-09-11,45.139,47500.00,1.0,5.0,1,200000 - 224999,1.0,1.0,1.0
2279970,2.213007e+11,1.0,5.213003e+11,1001.31,527.0,2021-06-23,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
2279991,2.213021e+11,1.0,5.213007e+11,745.21,5993.0,2006-07-06,72.641,32500.00,0.0,3.0,0,400000 - 449999,1.0,0.0,1.0
2280045,2.213024e+11,1.0,5.213009e+11,796.02,6291.0,2005-09-11,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
2280055,2.213024e+11,1.0,5.213009e+11,658.90,1436.0,2018-12-27,44.140,47500.00,0.0,4.0,0,150000 - 174999,0.0,0.0,1.0
2280061,2.213015e+11,1.0,5.213005e+11,1120.17,80.0,2022-09-13,55.444,80372.17,0.0,6.8,1,100000 - 124999,0.0,0.0,0.0
2280065,2.213003e+11,1.0,5.213001e+11,991.40,101.0,2022-08-23,45.473,62500.00,1.0,8.0,1,100000 - 124999,1.0,0.0,1.0
2280076,2.213032e+11,1.0,5.213015e+11,549.94,65.0,2022-09-28,35.806,125000.00,1.0,3.0,1,175000 - 199999,1.0,0.0,1.0
2280087,2.213002e+11,1.0,5.213001e+11,1515.77,81.0,2022-09-12,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
2280091,2.213002e+11,1.0,5.213001e+11,1072.48,6291.0,2005-09-11,96.222,37500.00,0.0,15.0,0,100000 - 124999,1.0,1.0,1.0
2280099,2.213019e+11,1.0,5.213007e+11,735.28,4830.0,2009-09-11,35.556,42500.00,1.0,4.0,0,100000 - 124999,0.0,1.0,1.0
2280117,2.213008e+11,1.0,5.213003e+11,725.62,80.0,2022-09-13,55.444,80372.17,0.0,6.8,1,250000 - 274999,0.0,0.0,1.0
2280120,2.213015e+11,1.0,5.213006e+11,714.57,80.0,2022-09-13,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
2280145,2.213032e+11,1.0,5.213014e+11,514.12,161.0,2022-06-24,55.444,87500.00,0.0,0.0,1,75000 - 99999,0.0,0.0,1.0
2280147,2.213029e+11,1.0,5.213011e+11,828.83,1204.0,2019-08-16,55.444,80372.17,0.0,1.0,1,75000 - 99999,1.0,0.0,1.0
2280158,2.213030e+11,1.0,5.213012e+11,142.64,80.0,2022-09-13,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
2280173,2.213017e+11,1.0,5.213006e+11,534.55,134.0,2022-07-21,54.557,125000.00,1.0,1.0,1,225000 - 249999,1.0,0.0,1.0
2280196,2.213033e+11,1.0,5.213015e+11,613.99,150.0,2022-07-05,58.891,17500.00,0.0,4.0,0,150000 - 174999,0.0,0.0,0.0
2280216,2.213015e+11,1.0,5.213006e+11,1138.64,6291.0,2005-09-11,55.440,80372.36,0.0,6.8,1,75000 - 99999,1.0,0.0,1.0
2280235,2.213031e+11,1.0,5.213013e+11,722.13,5608.0,2007-07-26,48.641,125000.00,0.0,6.0,0,250000 - 274999,1.0,0.0,1.0
2280238,2.213026e+11,1.0,5.213009e+11,1085.10,92.0,2022-09-01,43.053,70000.00,0.0,6.8,1,250000 - 274999,0.0,0.0,1.0
2280265,2.213010e+11,1.0,5.213004e+11,888.45,5516.0,2007-10-26,48.140,125000.00,1.0,6.0,1,225000 - 249999,1.0,0.0,1.0
2280275,2.213032e+11,1.0,5.213014e+11,1009.71,1204.0,2019-08-16,55.444,47500.00,0.0,0.0,1,75000 - 99999,0.0,0.0,1.0
2280282,2.213014e+11,1.0,5.213005e+11,866.20,140.0,2022-07-15,56.307,125000.00,1.0,15.0,1,125000 - 149999,1.0,0.0,1.0
2280290,2.213011e+11,1.0,5.213004e+11,1121.54,161.0,2022-06-24,55.444,80372.17,0.0,6.8,1,25000 - 49999,0.0,0.0,0.0
2280300,2.213006e+11,1.0,5.213002e+11,1257.56,98.0,2022-08-26,44.808,27500.00,1.0,6.8,0,25000 - 49999,0.0,1.0,0.0
2280308,2.213001e+11,1.0,5.213000e+11,931.09,6291.0,2005-09-11,82.557,47500.00,1.0,15.0,1,50000 - 74999,1.0,1.0,1.0

In [17]:
#col_names = [ 'CURR_ANN_AMT', 'DAYS_TENURE', 'AGE_IN_YEARS', 'INCOME', 'HAS_CHILDREN', 'LENGTH_OF_RESIDENCE',   'HOME_OWNER', 'COLLEGE_DEGREE', 'GOOD_CREDIT']
cols = ['CURR_ANN_AMT', 'DAYS_TENURE', 'AGE_IN_YEARS', 'INCOME', 'HAS_CHILDREN', 'LENGTH_OF_RESIDENCE',  'HOME_OWNER', 'COLLEGE_DEGREE', 'GOOD_CREDIT']
X = df_undersample[cols]
y = df_undersample.acct_terminated
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.598164104088

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

             precision    recall  f1-score   support

        0.0       0.60      0.59      0.60     80813
        1.0       0.60      0.60      0.60     80743

avg / total       0.60      0.60      0.60    161556

In [19]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [20]:
y_pred2 = rf.predict(X_test)
accuracy2 = accuracy_score(y_test, y_pred2)
print("Random Forest Accuracy:", accuracy2)

Random Forest Accuracy: 0.654262299141

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred2))

             precision    recall  f1-score   support

        0.0       0.63      0.76      0.69     80813
        1.0       0.70      0.55      0.61     80743

avg / total       0.66      0.65      0.65    161556