In [2]:
import pylab
import matplotlib
import pandas as pd
import numpy as np
import os

df = pd.read_csv("full_auto_insurance_data.csv")

In [3]:
display(df) #Original DF

,INDIVIDUAL_ID,acct_terminated,ADDRESS_ID,CURR_ANN_AMT,DAYS_TENURE,CUST_ORIG_DATE,AGE_IN_YEARS,DATE_OF_BIRTH,SOCIAL_SECURITY_NUMBER,LATITUDE,...,COUNTY,INCOME,HAS_CHILDREN,LENGTH_OF_RESIDENCE,MARITAL_STATUS,HOME_MARKET_VALUE,HOME_OWNER,COLLEGE_DEGREE,GOOD_CREDIT,ACCT_SUSPD_DATE
0,2.213000e+11,NaN,5.213000e+11,818.87,1454.0,2018-12-09,44.474,1978-06-23,608-XX-7640,32.578829,...,Kaufman,22500.00,1.0,15.0,Married,50000 - 74999,1.0,1.0,1.0,NaN
1,2.213001e+11,NaN,5.213001e+11,974.19,1795.0,2018-01-02,72.559,1950-05-30,342-XX-6908,32.732209,...,Dallas,27500.00,0.0,2.0,Single,50000 - 74999,1.0,0.0,0.0,NaN
2,2.213007e+11,NaN,5.213002e+11,967.37,4818.0,2009-09-23,55.444,1967-07-07,240-XX-9224,32.819777,...,Dallas,42500.00,0.0,10.0,Married,75000 - 99999,1.0,0.0,0.0,NaN
3,2.213016e+11,NaN,5.213006e+11,992.40,130.0,2022-07-25,53.558,1969-05-25,775-XX-6249,32.684065,...,Tarrant,125000.00,1.0,6.0,Married,175000 - 199999,1.0,0.0,1.0,2021-12-22
4,2.213016e+11,NaN,5.213006e+11,784.63,5896.0,2006-10-11,50.220,1972-09-25,629-XX-7298,32.751398,...,Tarrant,87500.00,1.0,4.0,Married,225000 - 249999,1.0,1.0,1.0,NaN
5,2.213027e+11,NaN,5.213010e+11,909.91,484.0,2021-08-05,32.641,1990-04-20,194-XX-6050,NaN,...,Dallas,52500.00,0.0,2.0,Married,125000 - 149999,1.0,0.0,1.0,NaN
6,2.213007e+11,NaN,5.213003e+11,1084.04,2896.0,2014-12-28,70.806,1952-02-29,653-XX-7262,33.006985,...,Denton,125000.00,1.0,8.0,Married,100000 - 124999,1.0,0.0,1.0,NaN
7,2.213022e+11,NaN,5.213008e+11,1277.37,4096.0,2011-09-15,45.969,1976-12-24,163-XX-1670,33.085901,...,Collin,47500.00,0.0,12.0,Married,125000 - 149999,1.0,0.0,1.0,NaN
8,2.213029e+11,NaN,5.213011e+11,917.20,2107.0,2017-02-24,56.389,1966-07-27,621-XX-5572,32.828468,...,Tarrant,47500.00,0.0,6.0,Single,50000 - 74999,1.0,1.0,1.0,2022-12-01
9,2.213012e+11,NaN,5.213005e+11,1095.39,3387.0,2013-08-24,64.307,1958-08-28,793-XX-1178,32.753978,...,Dallas,32500.00,0.0,15.0,Married,25000 - 49999,1.0,0.0,0.0,NaN
10,2.213015e+11,NaN,5.213005e+11,966.83,80.0,2022-09-13,55.444,1967-07-07,677-XX-1586,32.805436,...,Tarrant,80372.17,0.0,6.8,NaN,50000 - 74999,0.0,1.0,0.0,2022-09-16
11,2.213013e+11,NaN,5.213005e+11,905.03,5336.0,2008-04-23,66.639,1956-04-29,188-XX-6698,32.645107,...,Tarrant,125000.00,0.0,15.0,Married,125000 - 149999,1.0,1.0,1.0,NaN
12,2.213013e+11,NaN,5.213005e+11,619.60,1606.0,2018-07-10,NaN,1993-11-21,133-XX-4591,32.711729,...,Dallas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2.213031e+11,NaN,5.213013e+11,590.95,1606.0,2018-07-10,55.444,1967-07-07,777-XX-2081,NaN,...,Parker,70000.00,0.0,0.0,NaN,NaN,0.0,0.0,1.0,NaN
14,2.213020e+11,NaN,5.213007e+11,462.91,6020.0,2006-06-09,41.473,1981-06-22,299-XX-2622,33.089878,...,Denton,37500.00,1.0,6.0,Married,75000 - 99999,1.0,1.0,1.0,NaN
15,2.213028e+11,NaN,5.213010e+11,722.08,374.0,2021-11-23,69.139,1953-10-29,335-XX-8227,33.168202,...,Collin,62500.00,1.0,5.0,Single,100000 - 124999,1.0,1.0,1.0,NaN
16,2.213021e+11,NaN,5.213008e+11,569.83,107.0,2022-08-17,32.559,1990-05-20,277-XX-1871,32.854910,...,Tarrant,80372.17,0.0,6.8,NaN,150000 - 174999,0.0,1.0,1.0,NaN
17,2.213009e+11,NaN,5.213003e+11,961.04,80.0,2022-09-13,55.444,1967-07-07,563-XX-7554,NaN,...,Dallas,47500.00,0.0,0.0,NaN,NaN,0.0,0.0,1.0,2022-06-12
18,2.213014e+11,NaN,5.213005e+11,841.02,150.0,2022-07-05,59.053,1963-11-28,551-XX-2401,32.841713,...,Dallas,57500.00,0.0,11.0,Single,150000 - 174999,0.0,0.0,1.0,NaN
19,2.213015e+11,NaN,5.213005e+11,943.55,2409.0,2016-04-28,55.444,1967-07-07,455-XX-5888,NaN,...,Dallas,80372.17,0.0,6.8,NaN,250000 - 274999,0.0,0.0,1.0,NaN
20,2.213031e+11,NaN,5.213013e+11,741.67,4711.0,2010-01-08,43.723,1979-03-24,734-XX-3221,32.851905,...,Dallas,125000.00,1.0,10.0,Single,225000 - 249999,1.0,0.0,1.0,NaN
21,2.213015e+11,NaN,5.213005e+11,1398.72,5049.0,2009-02-04,40.969,1981-12-23,633-XX-7001,32.675671,...,Tarrant,125000.00,1.0,15.0,Married,75000 - 99999,1.0,1.0,1.0,NaN
22,2.213032e+11,NaN,5.213014e+11,913.66,6226.0,2005-11-15,60.559,1962-05-27,424-XX-2825,32.639399,...,Tarrant,47500.00,0.0,12.0,Married,50000 - 74999,1.0,0.0,1.0,NaN
23,2.213010e+11,NaN,5.213004e+11,438.24,1018.0,2020-02-18,48.893,1974-01-22,950-XX-8716,32.807283,...,Dallas,70000.00,0.0,6.0,Married,150000 - 174999,0.0,0.0,1.0,NaN
24,2.213008e+11,NaN,5.213003e+11,953.30,5463.0,2007-12-18,67.806,1955-02-28,585-XX-2402,32.869218,...,Tarrant,125000.00,0.0,9.0,Married,75000 - 99999,1.0,0.0,1.0,NaN
25,2.213024e+11,NaN,5.213009e+11,725.16,3336.0,2013-10-14,38.220,1984-09-22,423-XX-4997,32.841944,...,Tarrant,70000.00,0.0,7.0,Married,75000 - 99999,1.0,0.0,1.0,NaN
26,2.213000e+11,NaN,5.213000e+11,716.71,5654.0,2007-06-10,48.893,1974-01-22,479-XX-4835,NaN,...,Tarrant,87500.00,1.0,0.0,Single,NaN,0.0,0.0,0.0,2021-12-20
27,2.213020e+11,NaN,5.213007e+11,1103.39,6291.0,2005-09-11,NaN,1982-02-27,540-XX-5795,32.841068,...,Tarrant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2.213011e+11,NaN,5.213004e+11,795.03,2409.0,2016-04-28,55.444,1967-07-07,627-XX-9534,32.832474,...,Dallas,32500.00,0.0,6.8,NaN,75000 - 99999,0.0,0.0,1.0,NaN
29,2.213015e+11,NaN,5.213006e+11,1322.51,6291.0,2005-09-11,55.138,1967-10-27,250-XX-8931,NaN,...,Dallas,37500.00,1.0,7.0,Single,100000 - 124999,1.0,1.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2280291,2.213002e+11,NaN,5.213001e+11,1072.36,1813.0,2017-12-15,34.472,1988-06-21,630-XX-8564,NaN,...,Collin,125000.00,1.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN
2280292,2.213006e+11,NaN,5.213002e+11,908.39,3762.0,2012-08-14,59.138,1963-10-28,506-XX-6711,32.862185,...,Tarrant,47500.00,1.0,15.0,Married,75000 - 99999,1.0,0.0,1.0,NaN
2280293,2.213002e+11,NaN,5.213001e+11,1105.36,3101.0,2014-06-06,51.890,1971-01-24,364-XX-8511,32.683451,...,Tarrant,87500.00,1.0,12.0,Married,75000 - 99999,1.0,0.0,1.0,NaN
2280294,2.213003e+11,NaN,5.213001e+11,790.96,2385.0,2016-05-22,NaN,1983-04-19,505-XX-4395,32.918277,...,Dallas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2280295,2.213022e+11,NaN,5.213008e+11,1290.31,282.0,2022-02-23,56.559,1966-05-26,595-XX-3128,32.660717,...,Dallas,5000.00,1.0,15.0,Single,50000 - 74999,1.0,0.0,0.0,NaN
2280296,2.213002e+11,NaN,5.213001e+11,1251.92,506.0,2021-07-14,33.306,1989-08-20,782-XX-8679,32.758413,...,Kaufman,42500.00,0.0,15.0,Married,50000 - 74999,1.0,0.0,1.0,NaN
2280297,2.213030e+11,NaN,5.213012e+11,998.89,140.0,2022-07-15,56.389,1966-07-27,646-XX-6005,32.581784,...,Dallas,57500.00,1.0,5.0,Single,25000 - 49999,1.0,0.0,1.0,NaN
2280298,2.213012e+11,NaN,5.213005e+11,989.45,840.0,2020-08-14,43.472,1979-06-24,710-XX-2382,32.733825,...,Kaufman,125000.00,1.0,3.0,Single,125000 - 149999,1.0,1.0,1.0,NaN
2280299,2.213030e+11,NaN,5.213013e+11,918.77,3963.0,2012-01-26,45.054,1977-11-23,154-XX-9474,32.777825,...,Dallas,12500.00,1.0,4.0,Single,100000 - 124999,1.0,0.0,0.0,NaN
2280300,2.213006e+11,NaN,5.213002e+11,1257.56,98.0,2022-08-26,44.808,1978-02-21,795-XX-4476,33.040822,...,Parker,27500.00,1.0,6.8,Single,25000 - 49999,0.0,1.0,0.0,2021-12-23
2280301,2.213004e+11,NaN,5.213001e+11,726.39,2241.0,2016-10-13,42.472,1980-06-23,683-XX-5655,33.006400,...,Collin,87500.00,1.0,3.0,Married,200000 - 224999,1.0,0.0,1.0,NaN
2280302,2.213020e+11,NaN,5.213007e+11,808.34,4697.0,2010-01-22,69.388,1953-07-30,169-XX-1714,33.169976,...,Collin,70000.00,1.0,1.0,Married,125000 - 149999,1.0,0.0,1.0,NaN
2280303,2.213032e+11,NaN,5.213014e+11,591.31,2398.0,2016-05-09,31.053,1991-11-21,130-XX-4154,32.732201,...,Kaufman,12500.00,1.0,5.0,Single,1000 - 24999,0.0,0.0,1.0,NaN
2280304,2.213018e+11,NaN,5.213007e+11,832.68,88.0,2022-09-05,41.969,1980-12-23,281-XX-4340,32.649631,...,Tarrant,87500.00,1.0,4.0,Married,100000 - 124999,1.0,1.0,1.0,NaN
2280305,2.213000e+11,NaN,5.213000e+11,877.39,161.0,2022-06-24,55.444,1967-07-07,491-XX-1532,32.699260,...,Tarrant,80372.17,0.0,0.0,NaN,25000 - 49999,1.0,0.0,0.0,NaN
2280306,2.213005e+11,NaN,5.213002e+11,308.37,2061.0,2017-04-11,55.556,1967-05-27,556-XX-9387,32.953847,...,Denton,70000.00,1.0,14.0,Married,100000 - 124999,1.0,1.0,1.0,NaN
2280307,2.213031e+11,NaN,5.213013e+11,1047.71,6291.0,2005-09-11,57.221,1965-09-26,686-XX-4444,33.001304,...,Dallas,70000.00,1.0,2.0,Married,175000 - 199999,1.0,1.0,1.0,NaN
2280308,2.213001e+11,NaN,5.213000e+11,931.09,6291.0,2005-09-11,82.557,1940-06-02,386-XX-4360,32.940467,...,Rockwall,47500.00,1.0,15.0,Married,50000 - 74999,1.0,1.0,1.0,2022-03-26
2280309,2.213016e+11,NaN,5.213006e+11,510.96,278.0,2022-02-27,NaN,1998-06-27,575-XX-4965,32.896625,...,Tarrant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2280310,2.213023e+11,NaN,5.213008e+11,775.55,2097.0,2017-03-06,56.222,1966-09-26,740-XX-8182,32.859100,...,Tarrant,80372.17,0.0,1.0,Single,100000 - 124999,1.0,0.0,1.0,NaN
2280311,2.213004e+11,NaN,5.213001e+11,960.69,723.0,2020-12-09,55.444,1967-07-07,313-XX-4211,33.106566,...,Collin,70000.00,1.0,4.0,Single,100000 - 124999,1.0,0.0,1.0,NaN
2280312,2.213007e+11,NaN,5.213002e+11,1259.90,803.0,2020-09-20,55.444,1967-07-07,836-XX-1003,32.678483,...,Dallas,27500.00,1.0,3.0,Single,50000 - 74999,1.0,0.0,1.0,NaN
2280313,2.213015e+11,NaN,5.213005e+11,604.09,3261.0,2013-12-28,77.473,1945-07-01,498-XX-6384,32.972007,...,Dallas,87500.00,0.0,1.0,Married,125000 - 149999,1.0,0.0,1.0,NaN
2280314,2.213026e+11,NaN,5.213009e+11,1255.57,3403.0,2013-08-08,41.221,1981-09-22,960-XX-3949,32.902815,...,Dallas,125000.00,0.0,12.0,Married,125000 - 149999,1.0,1.0,1.0,NaN
2280315,2.213003e+11,NaN,5.213001e+11,1041.94,5341.0,2008-04-18,NaN,1980-05-07,764-XX-2229,NaN,...,Tarrant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2280316,2.213008e+11,NaN,5.213003e+11,1104.10,1258.0,2019-06-23,52.389,1970-07-26,730-XX-5654,32.892940,...,Tarrant,87500.00,1.0,11.0,Single,75000 - 99999,1.0,1.0,1.0,NaN
2280317,2.213004e+11,NaN,5.213001e+11,1189.74,142.0,2022-07-13,37.388,1985-07-22,306-XX-2712,33.184917,...,Collin,80372.17,0.0,6.8,NaN,100000 - 124999,0.0,1.0,1.0,NaN
2280318,2.213024e+11,NaN,5.213009e+11,362.14,1606.0,2018-07-10,55.444,1967-07-07,800-XX-2726,33.019653,...,Collin,80372.17,0.0,1.0,NaN,75000 - 99999,1.0,0.0,1.0,NaN
2280319,2.213006e+11,NaN,5.213002e+11,611.69,6291.0,2005-09-11,NaN,1998-11-09,198-XX-4107,33.038807,...,Collin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2280320,2.213016e+11,NaN,5.213006e+11,829.86,2504.0,2016-01-24,63.639,1959-04-29,520-XX-7573,33.146851,...,Denton,225000.00,1.0,4.0,Married,200000 - 224999,1.0,0.0,1.0,NaN

In [24]:
#Processing Data
df.loc[df['CURR_ANN_AMT'].isnull(), 'CURR_ANN_AMT'] = 931.06 #mean CURR_ANN_AMT is 931
df.loc[df['DAYS_TENURE'].isnull(), 'DAYS_TENURE'] = 3482.62 # mean DAYS_TENURE is 3482
df.loc[df['AGE_IN_YEARS'].isnull(), 'AGE_IN_YEARS'] = 55.44 # mean AGE_IN_YEARS is 55.44
df.loc[df['INCOME'].isnull(), 'INCOME'] = 80372.36 # mean INCOME is 80372.36
df.loc[df['HAS_CHILDREN'].isnull(), 'HAS_CHILDREN'] = 0.0 # mode HAS_CHILDREN is 0
df.loc[df['LENGTH_OF_RESIDENCE'].isnull(), 'LENGTH_OF_RESIDENCE'] = 6.80 # mean LENGTH_OF_RESIDENCE is 6.80
df.loc[df['MARITAL_STATUS'].isnull(), 'MARITAL_STATUS'] = "Married" # mode MARITAL_STATUS is Married
df.loc[df['HOME_MARKET_VALUE'].isnull(), 'HOME_MARKET_VALUE'] = "75000 - 99999" # mode HOME_MARKET_VALUE is 75000 - 99999
df.loc[df['HOME_OWNER'].isnull(), 'HOME_OWNER'] = 1 # mode HOME_OWNER is 1
df.loc[df['COLLEGE_DEGREE'].isnull(), 'COLLEGE_DEGREE'] = 0 # mode COLLEGE_DEGREE is 0
df.loc[df['GOOD_CREDIT'].isnull(), 'GOOD_CREDIT'] = 1 # mode GOOD_CREDIT is 1
df.loc[df['ACCT_SUSPD_DATE'].notnull(), 'ACCT_SUSPD_DATE'] = 1 #terminated=1
df.loc[df['ACCT_SUSPD_DATE'].isnull(), 'ACCT_SUSPD_DATE'] = 0 #not terminated=0
pd.set_option('display.max_columns', None) #Displays every column
df #Processed DF

#These data columns were not changed as I don't believe we are using them and changing them would be complicated.
#ADDRESS_ID was not changed
#CUST_ORIG_DATE was not changed
#DATE_OF_BIRTH was not changed
#SOCIAL_SECURITY_NUMBER was not changed
#LATITUDE & LONGITUDE were not changed
#STREET, CITY, STATE & COUNTY were not changed

,INDIVIDUAL_ID,acct_terminated,ADDRESS_ID,CURR_ANN_AMT,DAYS_TENURE,CUST_ORIG_DATE,AGE_IN_YEARS,DATE_OF_BIRTH,SOCIAL_SECURITY_NUMBER,LATITUDE,LONGITUDE,STREET_ADDRESS,CITY,STATE,COUNTY,INCOME,HAS_CHILDREN,LENGTH_OF_RESIDENCE,MARITAL_STATUS,HOME_MARKET_VALUE,HOME_OWNER,COLLEGE_DEGREE,GOOD_CREDIT,ACCT_SUSPD_DATE
0,2.213000e+11,NaN,5.213000e+11,818.87,1454.0,2018-12-09,44.474,1978-06-23,608-XX-7640,32.578829,-96.305006,52966 Welch Crescent,Kaufman,TX,Kaufman,22500.00,1.0,15.0,Married,50000 - 74999,1.0,1.0,1.0,1
1,2.213001e+11,NaN,5.213001e+11,974.19,1795.0,2018-01-02,72.559,1950-05-30,342-XX-6908,32.732209,-97.000893,46887 Lawrence Green,Grand Prairie,TX,Dallas,27500.00,0.0,2.0,Single,50000 - 74999,1.0,0.0,0.0,1
2,2.213007e+11,NaN,5.213002e+11,967.37,4818.0,2009-09-23,55.444,1967-07-07,240-XX-9224,32.819777,-96.846938,787 Daniel Mews Suite 806,Dallas,TX,Dallas,42500.00,0.0,10.0,Married,75000 - 99999,1.0,0.0,0.0,1
3,2.213016e+11,NaN,5.213006e+11,992.40,130.0,2022-07-25,53.558,1969-05-25,775-XX-6249,32.684065,-97.162180,9846 Shaw Manor Apt. 774,Arlington,TX,Tarrant,125000.00,1.0,6.0,Married,175000 - 199999,1.0,0.0,1.0,1
4,2.213016e+11,NaN,5.213006e+11,784.63,5896.0,2006-10-11,50.220,1972-09-25,629-XX-7298,32.751398,-97.376745,431 David Port Apt. 164,Fort Worth,TX,Tarrant,87500.00,1.0,4.0,Married,225000 - 249999,1.0,1.0,1.0,1
5,2.213027e+11,NaN,5.213010e+11,909.91,484.0,2021-08-05,32.641,1990-04-20,194-XX-6050,NaN,NaN,11358 Stephanie Station,Dallas,TX,Dallas,52500.00,0.0,2.0,Married,125000 - 149999,1.0,0.0,1.0,1
6,2.213007e+11,NaN,5.213003e+11,1084.04,2896.0,2014-12-28,70.806,1952-02-29,653-XX-7262,33.006985,-96.893972,9942 Rebecca Drive Apt. 512,Carrollton,TX,Denton,125000.00,1.0,8.0,Married,100000 - 124999,1.0,0.0,1.0,1
7,2.213022e+11,NaN,5.213008e+11,1277.37,4096.0,2011-09-15,45.969,1976-12-24,163-XX-1670,33.085901,-96.648596,58187 Roberson Walks,Allen,TX,Collin,47500.00,0.0,12.0,Married,125000 - 149999,1.0,0.0,1.0,1
8,2.213029e+11,NaN,5.213011e+11,917.20,2107.0,2017-02-24,56.389,1966-07-27,621-XX-5572,32.828468,-97.173721,2458 Darren Key,Bedford,TX,Tarrant,47500.00,0.0,6.0,Single,50000 - 74999,1.0,1.0,1.0,1
9,2.213012e+11,NaN,5.213005e+11,1095.39,3387.0,2013-08-24,64.307,1958-08-28,793-XX-1178,32.753978,-96.785564,32131 Robert Pike Suite 462,Dallas,TX,Dallas,32500.00,0.0,15.0,Married,25000 - 49999,1.0,0.0,0.0,1
10,2.213015e+11,NaN,5.213005e+11,966.83,80.0,2022-09-13,55.444,1967-07-07,677-XX-1586,32.805436,-97.357825,900 Walker Greens,Fort Worth,TX,Tarrant,80372.17,0.0,6.8,Married,50000 - 74999,0.0,1.0,0.0,1
11,2.213013e+11,NaN,5.213005e+11,905.03,5336.0,2008-04-23,66.639,1956-04-29,188-XX-6698,32.645107,-97.157319,7144 Gonzalez Island,Arlington,TX,Tarrant,125000.00,0.0,15.0,Married,125000 - 149999,1.0,1.0,1.0,1
12,2.213013e+11,NaN,5.213005e+11,619.60,1606.0,2018-07-10,55.440,1993-11-21,133-XX-4591,32.711729,-96.758175,610 Andrew Road,Dallas,TX,Dallas,80372.36,0.0,6.8,Married,75000 - 99999,1.0,0.0,1.0,1
13,2.213031e+11,NaN,5.213013e+11,590.95,1606.0,2018-07-10,55.444,1967-07-07,777-XX-2081,NaN,NaN,35088 Kelly Highway Apt. 034,Weatherford,TX,Parker,70000.00,0.0,0.0,Married,75000 - 99999,0.0,0.0,1.0,1
14,2.213020e+11,NaN,5.213007e+11,462.91,6020.0,2006-06-09,41.473,1981-06-22,299-XX-2622,33.089878,-96.874424,7275 Emily Plains,The Colony,TX,Denton,37500.00,1.0,6.0,Married,75000 - 99999,1.0,1.0,1.0,1
15,2.213028e+11,NaN,5.213010e+11,722.08,374.0,2021-11-23,69.139,1953-10-29,335-XX-8227,33.168202,-96.640185,151 Perkins Dale,Mckinney,TX,Collin,62500.00,1.0,5.0,Single,100000 - 124999,1.0,1.0,1.0,1
16,2.213021e+11,NaN,5.213008e+11,569.83,107.0,2022-08-17,32.559,1990-05-20,277-XX-1871,32.854910,-97.065069,741 James Squares Suite 860,Euless,TX,Tarrant,80372.17,0.0,6.8,Married,150000 - 174999,0.0,1.0,1.0,1
17,2.213009e+11,NaN,5.213003e+11,961.04,80.0,2022-09-13,55.444,1967-07-07,563-XX-7554,NaN,NaN,732 Duncan Crossroad,Grand Prairie,TX,Dallas,47500.00,0.0,0.0,Married,75000 - 99999,0.0,0.0,1.0,1
18,2.213014e+11,NaN,5.213005e+11,841.02,150.0,2022-07-05,59.053,1963-11-28,551-XX-2401,32.841713,-96.999883,01468 Joshua Bypass,Irving,TX,Dallas,57500.00,0.0,11.0,Single,150000 - 174999,0.0,0.0,1.0,1
19,2.213015e+11,NaN,5.213005e+11,943.55,2409.0,2016-04-28,55.444,1967-07-07,455-XX-5888,NaN,NaN,574 James Turnpike,Dallas,TX,Dallas,80372.17,0.0,6.8,Married,250000 - 274999,0.0,0.0,1.0,1
20,2.213031e+11,NaN,5.213013e+11,741.67,4711.0,2010-01-08,43.723,1979-03-24,734-XX-3221,32.851905,-96.808335,646 Hill Estates Suite 281,Dallas,TX,Dallas,125000.00,1.0,10.0,Single,225000 - 249999,1.0,0.0,1.0,1
21,2.213015e+11,NaN,5.213005e+11,1398.72,5049.0,2009-02-04,40.969,1981-12-23,633-XX-7001,32.675671,-97.364207,08323 Katie Avenue,Fort Worth,TX,Tarrant,125000.00,1.0,15.0,Married,75000 - 99999,1.0,1.0,1.0,1
22,2.213032e+11,NaN,5.213014e+11,913.66,6226.0,2005-11-15,60.559,1962-05-27,424-XX-2825,32.639399,-97.353364,24834 Mary Throughway,Fort Worth,TX,Tarrant,47500.00,0.0,12.0,Married,50000 - 74999,1.0,0.0,1.0,1
23,2.213010e+11,NaN,5.213004e+11,438.24,1018.0,2020-02-18,48.893,1974-01-22,950-XX-8716,32.807283,-96.598049,338 Nichols Junctions Suite 550,Mesquite,TX,Dallas,70000.00,0.0,6.0,Married,150000 - 174999,0.0,0.0,1.0,1
24,2.213008e+11,NaN,5.213003e+11,953.30,5463.0,2007-12-18,67.806,1955-02-28,585-XX-2402,32.869218,-97.172090,Unit 2131 Box 6527,Hurst,TX,Tarrant,125000.00,0.0,9.0,Married,75000 - 99999,1.0,0.0,1.0,1
25,2.213024e+11,NaN,5.213009e+11,725.16,3336.0,2013-10-14,38.220,1984-09-22,423-XX-4997,32.841944,-97.374225,2067 Frazier Village,Fort Worth,TX,Tarrant,70000.00,0.0,7.0,Married,75000 - 99999,1.0,0.0,1.0,1
26,2.213000e+11,NaN,5.213000e+11,716.71,5654.0,2007-06-10,48.893,1974-01-22,479-XX-4835,NaN,NaN,1223 Shelly Greens,Fort Worth,TX,Tarrant,87500.00,1.0,0.0,Single,75000 - 99999,0.0,0.0,0.0,1
27,2.213020e+11,NaN,5.213007e+11,1103.39,6291.0,2005-09-11,55.440,1982-02-27,540-XX-5795,32.841068,-97.405071,31250 Spencer Freeway,Fort Worth,TX,Tarrant,80372.36,0.0,6.8,Married,75000 - 99999,1.0,0.0,1.0,1
28,2.213011e+11,NaN,5.213004e+11,795.03,2409.0,2016-04-28,55.444,1967-07-07,627-XX-9534,32.832474,-96.660619,163 Kathryn Mountain,Dallas,TX,Dallas,32500.00,0.0,6.8,Married,75000 - 99999,0.0,0.0,1.0,1
29,2.213015e+11,NaN,5.213006e+11,1322.51,6291.0,2005-09-11,55.138,1967-10-27,250-XX-8931,NaN,NaN,61811 Buchanan Springs Suite 541,Garland,TX,Dallas,37500.00,1.0,7.0,Single,100000 - 124999,1.0,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2280291,2.213002e+11,NaN,5.213001e+11,1072.36,1813.0,2017-12-15,34.472,1988-06-21,630-XX-8564,NaN,NaN,USCGC Stout,Mckinney,TX,Collin,125000.00,1.0,0.0,Married,75000 - 99999,0.0,0.0,0.0,1
2280292,2.213006e+11,NaN,5.213002e+11,908.39,3762.0,2012-08-14,59.138,1963-10-28,506-XX-6711,32.862185,-97.340526,0281 David Brook Apt. 526,Fort Worth,TX,Tarrant,47500.00,1.0,15.0,Married,75000 - 99999,1.0,0.0,1.0,1
2280293,2.213002e+11,NaN,5.213001e+11,1105.36,3101.0,2014-06-06,51.890,1971-01-24,364-XX-8511,32.683451,-97.108577,936 Stevenson Island Suite 958,Arlington,TX,Tarrant,87500.00,1.0,12.0,Married,75000 - 99999,1.0,0.0,1.0,1
2280294,2.213003e+11,NaN,5.213001e+11,790.96,2385.0,2016-05-22,55.440,1983-04-19,505-XX-4395,32.918277,-96.649620,0143 Tara Loop,Garland,TX,Dallas,80372.36,0.0,6.8,Married,75000 - 99999,1.0,0.0,1.0,1
2280295,2.213022e+11,NaN,5.213008e+11,1290.31,282.0,2022-02-23,56.559,1966-05-26,595-XX-3128,32.660717,-96.759660,1580 Robbins Turnpike Apt. 541,Dallas,TX,Dallas,5000.00,1.0,15.0,Single,50000 - 74999,1.0,0.0,0.0,1
2280296,2.213002e+11,NaN,5.213001e+11,1251.92,506.0,2021-07-14,33.306,1989-08-20,782-XX-8679,32.758413,-96.288396,66705 Dennis Roads Apt. 360,Terrell,TX,Kaufman,42500.00,0.0,15.0,Married,50000 - 74999,1.0,0.0,1.0,1
2280297,2.213030e+11,NaN,5.213012e+11,998.89,140.0,2022-07-15,56.389,1966-07-27,646-XX-6005,32.581784,-96.518994,5641 Morgan Highway Apt. 284,Seagoville,TX,Dallas,57500.00,1.0,5.0,Single,25000 - 49999,1.0,0.0,1.0,1
2280298,2.213012e+11,NaN,5.213005e+11,989.45,840.0,2020-08-14,43.472,1979-06-24,710-XX-2382,32.733825,-96.468471,5749 Michael Station,Forney,TX,Kaufman,125000.00,1.0,3.0,Single,125000 - 149999,1.0,1.0,1.0,1
2280299,2.213030e+11,NaN,5.213013e+11,918.77,3963.0,2012-01-26,45.054,1977-11-23,154-XX-9474,32.777825,-96.914012,94044 Tyler Burg,Dallas,TX,Dallas,12500.00,1.0,4.0,Single,100000 - 124999,1.0,0.0,0.0,1
2280300,2.213006e+11,NaN,5.213002e+11,1257.56,98.0,2022-08-26,44.808,1978-02-21,795-XX-4476,33.040822,-97.788129,4940 John Passage,Springtown,TX,Parker,27500.00,1.0,6.8,Single,25000 - 49999,0.0,1.0,0.0,1
2280301,2.213004e+11,NaN,5.213001e+11,726.39,2241.0,2016-10-13,42.472,1980-06-23,683-XX-5655,33.006400,-96.509553,Unit 5331 Box 4781,Wylie,TX,Collin,87500.00,1.0,3.0,Married,200000 - 224999,1.0,0.0,1.0,1
2280302,2.213020e+11,NaN,5.213007e+11,808.34,4697.0,2010-01-22,69.388,1953-07-30,169-XX-1714,33.169976,-96.696020,73153 Matthew Pike,Mckinney,TX,Collin,70000.00,1.0,1.0,Married,125000 - 149999,1.0,0.0,1.0,1
2280303,2.213032e+11,NaN,5.213014e+11,591.31,2398.0,2016-05-09,31.053,1991-11-21,130-XX-4154,32.732201,-96.286284,5571 Brown Court Apt. 466,Terrell,TX,Kaufman,12500.00,1.0,5.0,Single,1000 - 24999,0.0,0.0,1.0,1
2280304,2.213018e+11,NaN,5.213007e+11,832.68,88.0,2022-09-05,41.969,1980-12-23,281-XX-4340,32.649631,-97.190810,219 Brandi Corner,Arlington,TX,Tarrant,87500.00,1.0,4.0,Married,100000 - 124999,1.0,1.0,1.0,1
2280305,2.213000e+11,NaN,5.213000e+11,877.39,161.0,2022-06-24,55.444,1967-07-07,491-XX-1532,32.699260,-97.323224,22659 Robinson Terrace Suite 083,Fort Worth,TX,Tarrant,80372.17,0.0,0.0,Married,25000 - 49999,1.0,0.0,0.0,1
2280306,2.213005e+11,NaN,5.213002e+11,308.37,2061.0,2017-04-11,55.556,1967-05-27,556-XX-9387,32.953847,-97.193224,9956 Burnett Place Apt. 697,Roanoke,TX,Denton,70000.00,1.0,14.0,Married,100000 - 124999,1.0,1.0,1.0,1
2280307,2.213031e+11,NaN,5.213013e+11,1047.71,6291.0,2005-09-11,57.221,1965-09-26,686-XX-4444,33.001304,-96.714526,1982 Mcclain Junctions,Richardson,TX,Dallas,70000.00,1.0,2.0,Married,175000 - 199999,1.0,1.0,1.0,1
2280308,2.213001e+11,NaN,5.213000e+11,931.09,6291.0,2005-09-11,82.557,1940-06-02,386-XX-4360,32.940467,-96.450533,1931 Ivan Tunnel,Rockwall,TX,Rockwall,47500.00,1.0,15.0,Married,50000 - 74999,1.0,1.0,1.0,1
2280309,2.213016e+11,NaN,5.213006e+11,510.96,278.0,2022-02-27,55.440,1998-06-27,575-XX-4965,32.896625,-97.103992,809 Scott Skyway Suite 842,Grapevine,TX,Tarrant,80372.36,0.0,6.8,Married,75000 - 99999,1.0,0.0,1.0,1
2280310,2.213023e+11,NaN,5.213008e+11,775.55,2097.0,2017-03-06,56.222,1966-09-26,740-XX-8182,32.859100,-97.288106,35379 Abigail Estates Suite 537,Fort Worth,TX,Tarrant,80372.17,0.0,1.0,Single,100000 - 124999,1.0,0.0,1.0,1
2280311,2.213004e+11,NaN,5.213001e+11,960.69,723.0,2020-12-09,55.444,1967-07-07,313-XX-4211,33.106566,-96.634325,646 Sullivan Crest,Allen,TX,Collin,70000.00,1.0,4.0,Single,100000 - 124999,1.0,0.0,1.0,1
2280312,2.213007e+11,NaN,5.213002e+11,1259.90,803.0,2020-09-20,55.444,1967-07-07,836-XX-1003,32.678483,-96.665119,5710 Amy Estates,Dallas,TX,Dallas,27500.00,1.0,3.0,Single,50000 - 74999,1.0,0.0,1.0,1
2280313,2.213015e+11,NaN,5.213005e+11,604.09,3261.0,2013-12-28,77.473,1945-07-01,498-XX-6384,32.972007,-96.688905,703 Charles Throughway Suite 274,Richardson,TX,Dallas,87500.00,0.0,1.0,Married,125000 - 149999,1.0,0.0,1.0,1
2280314,2.213026e+11,NaN,5.213009e+11,1255.57,3403.0,2013-08-08,41.221,1981-09-22,960-XX-3949,32.902815,-96.510684,13104 Patrick Via Suite 782,Rowlett,TX,Dallas,125000.00,0.0,12.0,Married,125000 - 149999,1.0,1.0,1.0,1
2280315,2.213003e+11,NaN,5.213001e+11,1041.94,5341.0,2008-04-18,55.440,1980-05-07,764-XX-2229,NaN,NaN,USCGC Alvarez,Fort Worth,TX,Tarrant,80372.36,0.0,6.8,Married,75000 - 99999,1.0,0.0,1.0,1
2280316,2.213008e+11,NaN,5.213003e+11,1104.10,1258.0,2019-06-23,52.389,1970-07-26,730-XX-5654,32.892940,-97.245317,11708 Rivera Groves Apt. 104,Keller,TX,Tarrant,87500.00,1.0,11.0,Single,75000 - 99999,1.0,1.0,1.0,1
2280317,2.213004e+11,NaN,5.213001e+11,1189.74,142.0,2022-07-13,37.388,1985-07-22,306-XX-2712,33.184917,-96.800328,813 Moore Dam,Frisco,TX,Collin,80372.17,0.0,6.8,Married,100000 - 124999,0.0,1.0,1.0,1
2280318,2.213024e+11,NaN,5.213009e+11,362.14,1606.0,2018-07-10,55.444,1967-07-07,800-XX-2726,33.019653,-96.597535,99844 Sandra Overpass,Wylie,TX,Collin,80372.17,0.0,1.0,Married,75000 - 99999,1.0,0.0,1.0,1
2280319,2.213006e+11,NaN,5.213002e+11,611.69,6291.0,2005-09-11,55.440,1998-11-09,198-XX-4107,33.038807,-96.733539,USNV Thomas,Plano,TX,Collin,80372.36,0.0,6.8,Married,75000 - 99999,1.0,0.0,1.0,1
2280320,2.213016e+11,NaN,5.213006e+11,829.86,2504.0,2016-01-24,63.639,1959-04-29,520-XX-7573,33.146851,-96.968217,9638 Singleton Highway Suite 699,Little Elm,TX,Denton,225000.00,1.0,4.0,Married,200000 - 224999,1.0,0.0,1.0,1